### ISSUE TITLE
How do I set the sender's name?

### ISSUE THREAD

**Issue by xzmshiji** [kootenpv/yagmail#128] opened 2018-10-19 09:39 UTC
How do I set the sender's name? For example, if the name of A is Tom and the email is sent to B, then the email received by B shows the email address of A, then what B wants to show is Tom!

**Comment by kootenpv** [comment] 2018-10-19 18:43
Sorry for the answer, but it is duplicate of this issue: https://github.com/kootenpv/yagmail/issues/114

**Closed** 2018-10-19 18:43 UTC
