### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by animismus** [kootenpv/yagmail#72] opened 2017-05-16 14:58 UTC
I'm not sure if this is just a py2 error, but I can't send unicode contents to yagmail

```
Traceback (most recent call last):

...
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\yagmail\yagmail.py", line 107, in send
    msg = self._prepare_message(addresses, subject, contents, attachments, headers)
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\yagmail\yagmail.py", line 230, in _prepare_message
    has_included_images, content_objects = self._prepare_contents(contents)
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\yagmail\yagmail.py", line 298, in _prepare_contents
    content_object = self._get_mime_object(content)
  File "C:\Program Files (x86)\Anaconda2\lib\site-packages\yagmail\yagmail.py", line 368, in _get_mime_object
    content_name = os.path.basename(str(content_string))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 2: ordinal not in range(128)
```

I tried removing the str() but then realized that the problem continues with, e.g., _prepare_message().

**Comment by kootenpv** [comment] 2017-05-16 20:32
I think it's related to the fact that you do not use utf8 at the moment, see:

http://stackoverflow.com/questions/30865978/encoding-problems-in-python-ascii-codec-cant-encode-character-xe3-when-u

**Comment by animismus** [comment] 2017-05-16 21:11
Maybe I don't understand what you are trying to tell me but if I do, for example:

```
u = unicode("melão!", "utf-8")
str(u)
```

I still get the same error I am getting from yagmail, because it is trying to do the same thing str() on a unicode/utf8 string.

**Comment by kootenpv** [comment] 2017-05-17 08:41
I think you have to decode your data from the encoding you have, and encode it as utf8, but I'm not sure myself.

**Comment by carlyd95** [comment] 2017-07-22 17:32
I also would like to be able to send Unicode HTML via yagmail @kootenpv

"self._prepare_contents(contents)
  File "/usr/lib/python2.7/site-packages/yagmail/sender.py", line 305, in _prepare_contents
    content_object = self._get_mime_object(content)
  File "/usr/lib/python2.7/site-packages/yagmail/sender.py", line 375, in _get_mime_object
    content_name = os.path.basename(str(content_string))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 324: ordinal not in range(128)" is the end of the error code. Is there a way for you to add options to pass Unicode instead of just str's? Thanks! :)

**Comment by kootenpv** [comment] 2017-07-22 18:07
I believe it is fixed as of `yagmail-0.9.179`

@carlyd95 Could you `pip install -U yagmail` and let me know if the problem is solved?

**Comment by carlyd95** [comment] 2017-07-22 19:30
@kootenpv I still get same error

**Comment by kootenpv** [comment] 2017-07-22 19:44
@carlyd95 Could you perhaps post a minimal example of some content that you are sending that doesn't work?

**Comment by carlyd95** [comment] 2017-07-23 21:00
You just have to change it to a str before sending it, which is fine I just couldn't figure it out at first.  Thanks for the help! :)

For others who are learning like me:
>>>t = u"\u2014"
>>>type(t)
>>><type 'unicode'>
>>>type(t.encode('utf8'))
>>><type 'str'>

**Comment by kootenpv** [comment] 2017-07-23 21:30
@carlyd95 great that you got it working :)

The example that I had in mind that worked:

```python
import yagmail
yagmail.SMTP().send(contents=u"<h1>\u2013</h1>")
```
In case anyone feels like they want to add to this case, please reopen.

**Closed by kootenpv** 2017-07-23 21:30 UTC

**Comment by Nwizy11** [comment] 2018-09-10 07:55
I've the same issue.
